### ISSUE TITLE
关于cookies

### ISSUE THREAD

**Issue by log2cn** [Do1e/NJU_Health-Checkin#1]
authserver和ehall的cookies都是临时的。
建议使用app的cookies，这是永久的。

**Comment by Do1e** [comment]
> authserver和ehall的cookies都是临时的。 建议使用app的cookies，这是永久的。

刚刚更新好了，目前的版本使用的是APP的cookie，但是获取cookie要抓包

**Comment by Do1e** [comment]
当前版本使用的即为app的cookies

**Comment by log2cn** [comment]
感谢支持！
