### ISSUE TITLE
关于每天执行两次action

### ISSUE THREAD

**Issue by log2cn** [Do1e/NJU_Health-Checkin#19]
为防止随机性错误，我之前设置了每日执行2次action，但查看最近4天的记录发现，你我每天只执行了一次，是何原因？

**Comment by Do1e** [comment]
> 为防止随机性错误，我之前设置了每日执行2次action，但查看最近4天的记录发现，你我每天只执行了一次，是何原因？

中午12点是一个热门的时间段，可能确实容易不执行

**Comment by Do1e** [comment]
> 为防止随机性错误，我之前设置了每日执行2次action，但查看最近4天的记录发现，你我每天只执行了一次，是何原因？

更改成非整点的冷门时间应该会有改善

**Comment by log2cn** [comment]
谢谢
