### ISSUE TITLE
希望增加github action的部署功能

### ISSUE THREAD

**Issue by log2cn** [Do1e/NJU_Health-Checkin#2]

**Comment by Do1e** [comment]
> _No description provided._

已完成，但目前时间不能打卡，因此并没有通过测试，等白天再测试以下看看行不行。

**Comment by Do1e** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/73533898/187973477-3c9475d0-bc93-4cf4-a261-02c1578b702f.png)

好消息是可以用了，坏消息是似乎cookie并不是固定的。。。
