### ISSUE TITLE
建议添加'UTC'时区支持

### ISSUE THREAD

**Issue by YikeZhou** [Do1e/NJU_Health-Checkin#22]
`yesterday`计算方法与`'中国'`和`'China'`相同，测试代码如下：

```python
>>> import time, datetime
>>> time.strftime('%Z', time.gmtime())
'UTC'
>>> datetime.datetime.now()
datetime.datetime(2022, 10, 19, 10, 35, 30, 112328)  # 返回值与本地时间一致
```

Python版本：
```
Python 3.9.7 (default, Oct 12 2021, 10:15:30) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

操作系统版本：macOS Big Sur 11.7

**Comment by Do1e** [comment]
> `yesterday`计算方法与`'中国'`和`'China'`相同，测试代码如下：
> 
> ```python
> >>> import time, datetime
> >>> time.strftime('%Z', time.gmtime())
> 'UTC'
> >>> datetime.datetime.now()
> datetime.datetime(2022, 10, 19, 10, 35, 30, 112328)  # 返回值与本地时间一致
> ```
> 
> Python版本：
> 
> ```
> Python 3.9.7 (default, Oct 12 2021, 10:15:30) 
> [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> ```
> 
> 操作系统版本：macOS Big Sur 11.7

手边没有mac设备不太好测试。这UTC也太模糊了，中国时间理论上是UTC+8才对。

**Comment by Do1e** [comment]
已经更新时区的获取方式，可以测试一下，理论上兼容更多平台。
