### ISSUE TITLE
action运行失败，提示locatin相关的问题

### ISSUE THREAD

**Issue by 6yhn** [Do1e/NJU_Health-Checkin#23]
https://github.com/6yhn/NJU_Health-Checkin/actions

关于环境：
我的secret设置了location.

**Comment by 6yhn** [comment]
感觉原因可能是近14天没有每天打卡

**Comment by Do1e** [comment]
已于[加强打卡地址检测的健壮性](https://github.com/Do1e/NJU_Health-Checkin/commit/4ab06858489a81db85bdc57ea673019e89016f68)中修复，请merge一下或者重新fork
