### ISSUE TITLE
contab -e 在哪个文件中

### ISSUE THREAD

**Issue by estarpro1022** [Do1e/NJU_Health-Checkin#24]
现在还有设置contab -e的必要吗，我在文件中找了一圈没找到

**Comment by Do1e** [comment]
不好意思，这里写错了，应该是`crontab -e`。这是一个linux的命令，用于在Linux上部署。

![image](https://user-images.githubusercontent.com/73533898/200869002-9797b8a2-6296-49b1-bd9b-b761502a05d9.png)
![image](https://user-images.githubusercontent.com/73533898/200869567-4f8203e2-4a35-4a14-bf6d-2eaa591bb473.png)

如果没有Linux主机建议按照Github Action的步骤进行部署，参见README的小标题Github Action下的内容。
