### ISSUE TITLE
打卡出现未知错误

### ISSUE THREAD

**Issue by estarpro1022** [Do1e/NJU_Health-Checkin#26]
https://img.kartone.site/img/image-20221126134700047.png
昨天出现了这个未知错误，并且我的邮箱收到了一封打卡失败的邮件，当时没在意。自动打卡从11.9就正常打卡，但是不知道为什么昨天就寄掉了。
我没有修改登录密码，也没有做其他操作，但是它就是失败了。今天又收到一封，赶紧到GitHub来看，发现失败了

**Comment by Do1e** [comment]
> https://img.kartone.site/img/image-20221126134700047.png 昨天出现了这个未知错误，并且我的邮箱收到了一封打卡失败的邮件，当时没在意。自动打卡从11.9就正常打卡，但是不知道为什么昨天就寄掉了。 我没有修改登录密码，也没有做其他操作，但是它就是失败了。今天又收到一封，赶紧到GitHub来看，发现失败了

在最新的代码中已经没有未知错误了，请更新到最新的版本。

以及我看你最近的记录都是有明确的报错原因的

![image](https://user-images.githubusercontent.com/73533898/204079713-1f6497a8-ac2a-4c2e-adc1-824250672cbb.png)
