### ISSUE TITLE
actions报错

### ISSUE THREAD

**Issue by log2cn** [Do1e/NJU_Health-Checkin#6]
https://github.com/191840239/NJU_Health-Checkin/runs/8149762922?check_suite_focus=true

**Comment by Do1e** [comment]
> https://github.com/191840239/NJU_Health-Checkin/runs/8149762922?check_suite_focus=true

这里是上次打卡地址获取错误，尝试手机打卡一次再运行呢？

**Comment by Do1e** [comment]
不过很奇怪，本地基本不出错，在actions上有各种各样的问题

**Comment by log2cn** [comment]
我的action仍不成功，报connection timeout，悲伤，555。

**Comment by Do1e** [comment]
> {'personId': '', 'userId': '', 'authId': '', 'openId': '', 'name': '', 'tenantId': 'nju', 'tenantName': '', 'mobile': 'XXXXXXXXXXX', 'userType': 'STUDENT', 'status': 'cpdailyPage', 'authStatus': '', 'deviceStatus': 'exception', 'deviceExceptionMsg': '抱歉，这不是小i认识的那台手机了，出于安全，我们将发出一条通知短信。如果是您本人操作，请忽略。', 'tgcStatus': '', 'tgc': '', 'sessionToken': '', 'completeUserInfoStatus': '', 'firstLogin': False}
> 南大app登录失败

似乎登录出问题了

**Comment by Do1e** [comment]
> > {'personId': '', 'userId': '', 'authId': '', 'openId': '', 'name': '', 'tenantId': 'nju', 'tenantName': '', 'mobile': 'XXXXXXXXXXX', 'userType': 'STUDENT', 'status': 'cpdailyPage', 'authStatus': '', 'deviceStatus': 'exception', 'deviceExceptionMsg': '抱歉，这不是小i认识的那台手机了，出于安全，我们将发出一条通知短信。如果是您本人操作，请忽略。', 'tgcStatus': '', 'tgc': '', 'sessionToken': '', 'completeUserInfoStatus': '', 'firstLogin': False}
> > 南大app登录失败
> 
> 似乎登录出问题了

已修复，目前为新的登录问题，感觉应该是url_service的问题：

> Traceback (most recent call last):
>   File "checkin.py", line 108, in <module>
>     result = main()
>   File "checkin.py", line 79, in main
>     auth.login_mobile()
>   File "auth_login.py", line 82, in login_mobile
>     self.get_login_init(url_service)
>   File "auth_login.py", line 36, in get_login_init
>     self.pwdDefaultEncryptSalt = re.search("\"pwdDefaultEncryptSalt\" value=\"(.+?)\"", r.text).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by log2cn** [comment]
抱歉，这不是小i认识的那台手机了，出于安全，我们将发出一条通知短信。如果是您本人操作，请忽略。
关于这个问题可能的远因是：南大app只能单处登录，若一处已经登录的情况下在另一处登录会触发这个问题。正在寻找解决方案。

下面的问题我暂时没有复现出来。

**Comment by Do1e** [comment]
> 抱歉，这不是小i认识的那台手机了，出于安全，我们将发出一条通知短信。如果是您本人操作，请忽略。 关于这个问题可能的远因是：南大app只能单处登录，若一处已经登录的情况下在另一处登录会触发这个问题。正在寻找解决方案。
> 
> 下面的问题我暂时没有复现出来。

不认识手机的问题可以通过配置User_Agent解决

**Comment by log2cn** [comment]
请问应该将user_agent设置成什么？

**Comment by Do1e** [comment]
> 请问应该将user_agent设置成什么？

见README->抓包方法

**Comment by log2dx** [comment]
设置user_agent的方法有效！
下一个问题也复现并解决了，稍后上传。

**Comment by log2cn** [comment]
这个问题的来龙去脉我已经弄清了，稍后上传修改后的代码。

**Comment by Do1e** [comment]
已完成
